cumle=input("bir cumle giriniz:")
karakter_sayisi=len(cumle.replace(" " ,""))
print("Cumledeki karakter sayisi(bosluksuz):",karakter_sayisi)
kelimeler=cumle.split()
kelime_sayisi=len(kelimeler)
print("kelime sayisi:",kelime_sayisi)
benzersiz_kelimeler=set(kelimeler)
print("benzersiz kelimeler:",benzersiz_kelimeler)
print("benzersiz kelime sayisi:", len(benzersiz_kelimeler))
en_uzun_kelime=max(kelimeler,key=len)
print("en uzun kelime:",en_uzun_kelime)
